# Generated by Django 4.2.11 on 2024-03-13 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Kick_Off', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_ticket_price',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
