# Generated by Django 4.2.11 on 2024-03-09 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kick_Off', '0002_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='event_time',
            field=models.TimeField(),
        ),
    ]
