# Generated by Django 4.2.11 on 2024-03-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kick_Off', '0002_event_event_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_ticket_price',
            field=models.IntegerField(),
        ),
    ]
