# Generated by Django 4.2.11 on 2024-03-14 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kick_Off', '0003_alter_event_event_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_eventss', to='Kick_Off.event'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_participants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_number_of_tickets', models.IntegerField()),
                ('event_ticket_price', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_events', to='Kick_Off.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_participants', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
