# Generated by Django 4.2.11 on 2024-03-10 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Kick_Off', '0006_alter_events_event_location_link'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Events',
            new_name='Event',
        ),
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='KickOffCustomUser',
        ),
    ]
