# Generated by Django 4.2.11 on 2024-03-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kick_Off', '0007_rename_event_rating_rating_event_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
