# Generated by Django 4.2.11 on 2024-03-10 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('Kick_Off', '0008_rename_kickoffcustomuser_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='KickOffUser',
        ),
    ]
