# Generated by Django 4.2.11 on 2024-04-20 11:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Kick_Off', '0008_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_image_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_video_url',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
