# Generated by Django 4.2.11 on 2024-03-10 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kick_Off', '0010_rename_kickoffuser_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_organization',
            new_name='is_organisation',
        ),
    ]
