# Generated by Django 4.2.11 on 2024-03-10 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Kick_Off', '0012_carts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Carts',
            new_name='Cart',
        ),
    ]
